spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.108.41.238:3306/test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: gaomi
    password: u7i8o9p0
  jooq:
    sql-dialect: mysql_5_7